apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: security@soprun.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # example: cross-account zone management for example.com
      # this solver uses ambient credentials (i.e. inferred from the environment or EC2 Metadata Service)
      # to assume a role in a different account
      - selector:
          dnsZones:
            - "soprun.com"
        dns01:
          route53:
            region: ap-south-1
            hostedZoneID: 71MYVttggee
            role: arn:aws:iam::123456:role/dns-manager
