apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-webserver"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-webserver"
    app.kubernetes.io/tier: "frontend"
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-persistent-volume-claim
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-webserver"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-webserver
  labels:
    app.kubernetes.io/name: "wordpress"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-webserver"
    app.kubernetes.io/tier: "frontend"
  annotations:
    kubernetes.io/application: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "wordpress"
      app.kubernetes.io/version: "3"
      app.kubernetes.io/component: "wordpress-webserver"
      app.kubernetes.io/tier: "frontend"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "wordpress"
        app.kubernetes.io/version: "3"
        app.kubernetes.io/component: "wordpress-webserver"
        app.kubernetes.io/tier: "frontend"
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wordpress-database
              key: DATABASE_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-database
              key: DATABASE_USERNAME
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-database
              key: DATABASE_PASSWORD
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-database
              key: DATABASE_NAME
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-persistent-volume-claim
