apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
# namespace: application-system

# namePrefix: application-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: wordpress

resources:
  - deployment.yaml

configMapGenerator:
  - name: wordpress-vars
    literals:
      - APP_DOMAIN=soprun.com
      - APP_URL=https://soprun.com
      - APP_FROM_EMAIL=no-reply@soprun.com
      - APP_USER_EMAIL=mail@soprun.com
      - APP_EMAIL_USERNAME=john@gmail.com
      - APP_EMAIL_PASSWORD=password
      - APP_EMAIL_SMTP=smtp.gmail.com
      - APP_EMAIL_PORT=587
      - APP_EMAIL_ENCRYPTION=TLS

#secretGenerator:
#  - name: wordpress-secret
#    literals:
#      - APP_SECRET=secret
#      - DATABASE_HOST=localhost
#      - DATABASE_USERNAME=john
#      - DATABASE_PASSWORD=secret
#      - DATABASE_NAME=sandbox
