# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-hsvc
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "mysql-hsvc"
    app.kubernetes.io/tier: "backend"
spec:
  ports:
    - port: 3306
  selector:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/component: "mysql-rdbms"
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-mysql
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "mysql-rdbms"
    app.kubernetes.io/tier: "backend"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "wordpress-01"
      app.kubernetes.io/component: "mysql-rdbms"
      app.kubernetes.io/tier: "backend"
  replicas: 1
  serviceName: wordpress-mysql-hsvc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "wordpress-01"
        app.kubernetes.io/component: "mysql-rdbms"
        app.kubernetes.io/tier: "backend"
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        storageClassName: manual
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
