# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-webserver-svc
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-svc"
    app.kubernetes.io/tier: "frontend"
spec:
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/component: "wordpress-webserver"
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-webserver-hsvc
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-hsvc"
    app.kubernetes.io/tier: "frontend"
spec:
  ports:
    - port: 3306
  selector:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/component: "wordpress-webserver"
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-webserver
  labels:
    app.kubernetes.io/name: "wordpress-01"
    app.kubernetes.io/version: "3"
    app.kubernetes.io/component: "wordpress-webserver"
    app.kubernetes.io/tier: "frontend"
  annotations:
    kubernetes.io/application: wordpress
spec:
  replicas: 1
  serviceName: wordpress-webserver-hsvc
  selector:
    matchLabels:
      app.kubernetes.io/name: "wordpress-01"
      app.kubernetes.io/component: "wordpress-webserver"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "wordpress-01"
        app.kubernetes.io/version: "3"
        app.kubernetes.io/component: "wordpress-webserver"
        app.kubernetes.io/tier: "frontend"
    spec:
      containers:
        - image: wordpress:4.8-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql-hsvc
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
  volumeClaimTemplates:
    - metadata:
        name: wordpress-persistent-storage
      spec:
        storageClassName: manual
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
